
export const MESSAGE_REQUEST= "MESSAGE_REQUEST";
export const MESSAGE_SUCCESS= "MESSAGE_SUCCESS";
export const CONTACT_SUCCESS= "CONTACT_SUCCESS";
export const MESSAGE_FAIL= "MESSAGE_FAIL";
export const SAVE_MESSAGES_SUCCESS = "SAVE_MESSAGES_SUCCESS";
export const DELETE_MESSAGES_SUCCESS = "DELETE_MESSAGES_SUCCESS";
